### ISSUE TITLE
LCD Number

### ISSUE THREAD

**Issue by xinlangzi** [pracstrat/Internship#1]
Write a program that displays LCD style numbers.

For example, if your program is called with:

`$ ruby lcd.rb 0 1`

```
 --
|  |

|  |
 --

```

`$ ruby lcd.rb 02 2`

```
 ----    ---  
|    |      |
|    |      |
         ---
|    |  | 
|    |  | 
 ----    ---
```

**Comment by xinlangzi** [comment]
Please package the lcd code by using class, variable.

**Comment by xinlangzi** [comment]
You can try this [llink](http://tryruby.org/levels/1/challenges/0) to try ruby.

**Comment by xinlangzi** [comment]
@FrankXie2012 

Frank: Print the LCD in horizontal line.

Such as:

```
--        --   --        -- 
|  |    |    |    | |  | |   
|  |    |    |    | |  | |   
           --   --   --   -- 
|  |    | |       |    |    |
|  |    | |       |    |    |
 --        --   --        -- 
```

**Comment by xinlangzi** [comment]
@jianghy 

Gray: Give the params to adjust the size of output LCD number

Such as:

```
 --
|  |
 --
|  |
 --
```

```
 ----
|    |
|    |
 ----
|    |
|    |
 ----
```

**Comment by xinlangzi** [comment]
@seven1 

Seven: Print the LCD in color.

Code:

```
lcd = Lcd.new(123)
lcd.display('red')      # Display 123 in red color
lcd.display('white')   # Display 123 in white color
```

**Comment by linjunpop** [comment]
几点关于 Style 的建议：
1. Ruby 的代码缩进用的是两个空格，千万不要用 tab 或者不等于两个空格来缩进！！
2. 程序中没有用的代码，不要注释掉，应该直接删除掉，留下注释掉的代码会让读代码的人困惑。

为什么要这样呢？因为 虽然 你的代码是给机器执行的，但是你写的代码最终是给人看的。

推荐去看一看：

http://coding.smashingmagazine.com/2012/10/25/why-coding-style-matters/

https://github.com/bbatsov/ruby-style-guide

https://github.com/JuanitoFatas/ruby-style-guide/blob/master/README-zhCN.md 简体版本

https://github.com/rocodev/guides

Follow your :heart:

/cc @pracstrat/developers

**Comment by haobole** [comment]
@lgy123 ,

Please do this!
